name: CD

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: CamiloGarciaLaRotta/watermelon-http-client@v1
      #   id: request
      #   with:
      #     url: "https://spyfall.tannerkrewson.com/lock"
      #     method: post
      #     headers: '{"Content-Type": "application/json" }'
      #     data: '{ "password": "${{ secrets.ADMIN_PASSWORD }}" }'

      # - name: Print the response code of the lock
      #   run: echo ${{ steps.request.outputs.status }}
      #   shell: bash

      # - name: Wait 10 minutes for in-progress games to finish up (wait 8m + 2m for deploy)
      #   uses: jakejarvis/wait-action@v0.1.0
      #   with:
      #     time: "8m"

      - uses: actions/checkout@v4
        with:
          ref: "prod"
          fetch-depth: "0"

      - name: Dokku deploy
        uses: dokku/github-action@v1
        with:
          git_push_flags: "--force"
          git_remote_url: "ssh://dokku@134.209.222.77:22/spyfall"
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          branch: "prod"
